### ISSUE TITLE
URL https://docu.scout.ch 👍 👎 

### ISSUE THREAD

**Issue by Michael-Schaer** [scout-ch/docu#16]
Wir sollten der Webseite eine passende URL vergeben. Das ist mit GitHub Pages recht einfach gemacht.

Vorschlag: https://docu.scout.ch

Einwände? Andere Ideen?

**Comment by Vento-Nuenenen** [comment]
docu. Find ich in Ordnung.
Könnte auch doc. oder wiki. sein.
